import { Inter } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const className = twMerge('bg-black', inter.className)
  return (
    <html lang="en">
      <body className={className}>{children}</body>
    </html>
  );
}
